### ISSUE TITLE
Pagina "Login y Registro"

### ISSUE THREAD

**Issue by tomi6k** [GrupoSegundaEtapa/Proyecto#13]
Apartado donde se podrá crear una cuenta para el uso de la pagina y se podrá iniciar sesión en una ya creada.

Opcional: Inicio de Sesion y Registro via Facebook, Google, Twitter, etc.

**Comment by sgtbranca** [comment]
Actividad realizada correctamente, implemente tecnologías como: Bootstrap, JQuery y JavaScript.
Opcional: Implemente el logueo con Gmail de Google, ya que quise implementar también Facebook pero necesitaba permisos de API's que no pude conseguirlos ya que las direcciones URI que puse son de localhost únicamente. Una vez terminada la pagina y ya en línea en WWW podré activar el acceso con demás redes sociales
