### ISSUE TITLE
[Documentación] 1.2 Alcance

### ISSUE THREAD

**Issue by sqlote** [GrupoSegundaEtapa/Proyecto#19]
"Esta especificación de requisitos está dirigida al usuario del sistema, ………………" 

(Completar con el tipo de alcance que se busca alcanzar con el proyecto)

**Comment by Sandpatri1** [comment]
El proyecto consiste en un sitio web que brinda cursos de capacitaciones, actualización y perfeccionamieto del idioma inglés. Brinda conocimientos de los diversos temas para todos los niveles. El usuario podrá seguir los cursos de forma online, gestionando su propio tiempo de aprendizaje. El sitio tendrá actividades para realizar, como tutoriales, diccionarios, y ejemplos. También contará con un formulario web para la inscripción a los distintos cursos de inglés. Algunos cursos podrán certificación a nombre de la persona que lo realize.

**Comment by recursosssbb** [comment]
El proyecto consiste en un sitio web que brinda cursos de capacitaciones, actualización y perfeccionamieto del idioma inglé segun el nivel de aprendizaje. El usuario podrá seguir los cursos de forma  100% online, gestionando sus tiempos y espacios de estudio. El sitio tendrá actividades para realizar, como tutoriales, diccionarios, ejemplos y otras herramientas de aprendizaje centrados en el estudiante como foros de preguntas frecuentes y otros colaborativos por niveles. También contará con un formulario web para la inscripción a los distintos cursos de inglés. Segun el curso se podra certificar a nombre de la persona que lo realize por la Academia

**Comment by Sandpatri1** [comment]
ALCANCE DEL PROYECTO
El proyecto consiste en un sitio web que brinda cursos de capacitaciones, actualizaciones y perfeccionamientos del idioma inglés según el nivel de aprendizaje. El usuario podrá seguir los cursos de forma 100% bajo la modalidad online, gestionando sus tiempos, espacios de estudio y ritmo de aprendizajes. 
El sitio se focalizará en las cuatro destrezas principales: habla y pronunciación, lectura, escritura y gramática, pondrá a disposición y compartirá una serie de entregas de propuestas didácticas para su puesta en práctica, como tutoriales, diccionarios, ejemplos y otras herramientas, para favorecer  la construcción de los saberes tales como: foros de preguntas frecuentes para el intercambio y otros colaborativos por niveles, contemplando la flexibilidad de conocimientos  de la lengua extranjera. También contará con un formulario web para la inscripción a los distintos cursos de inglés. Según el curso se podrá certificar a nombre de la persona que lo realice por la Academia.
