### ISSUE TITLE
#US3 #1.3 Personal Involucrado

### ISSUE THREAD

**Issue by sqlote** [GrupoSegundaEtapa/Proyecto#20]
(Completar con el personal involucrado al proyecto)

**Comment by recursosssbb** [comment]
[1-3_Personal involucrado.pdf](https://github.com/GrupoSegundaEtapa/Proyecto/files/9693243/1-3_Personal.involucrado.pdf)

**Comment by recursosssbb** [comment]
Me parecio un trabajo interesante, para conocer a fondo la norma IEEE-830 y cada uno de sus apartados aplicados a nuestro proyecto como si éste fuera un proyecto real.
