### ISSUE TITLE
#US1 #2.2 Caracteristicas de los usuarios

### ISSUE THREAD

**Issue by sqlote** [GrupoSegundaEtapa/Proyecto#25]
(Completar con las características que deben tener cada tipo de usuario que utilizara la aplicación web)

**Comment by GrupoSegundaEtapa** [comment]
Documenté el iee-830 con las características de los usuarios que navegarán por la pagina, especificando en una tabla el tipo de usuario, tipo de rol y permisos. Un poco difícil realizar la tabla con especificaciones, me hizo pensar más a fondo el diagrama de bases de datos para poder guiarme próximamente en siguientes issues. En HTML no he tenido problema aún, me queda por realizar el style del login/registro con CSS, de la paleta de color ya seleccionada.
