### ISSUE TITLE
Barra de navegacion superior del Campus.

### ISSUE THREAD

**Issue by tomi6k** [GrupoSegundaEtapa/Proyecto#34]
Como usuario del campus virtual, quiero que en la barra de navegacion superior tenga acceso a las notificaciones, mensajes, menu principal y mi perfil de usuario donde modificar mis datos y ver el tablero inicial.

**Comment by sgtbranca** [comment]
Realizado correctamente con lo pedido. Quedó un poco vaga la presentación pero con los proximos sprints se podrá pulir aún más, el roadmap de usuarios está diagramado. Solo faltan algunos puntos que reforzar y luego pasarlo a codigo limpio.
